name: Node.js CI/CD with SAST and DAST 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    
    - name: Install dependencies
      run: npm install

    - name: Run SAST
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Make sure Python 3 is installed
    - run: pip install bandit # Install Bandit
    - run: bandit -r . -f json -o sast-report.json # Run Bandit and save the report

    - name: Run DAST
      run: |
        # Use OWASP ZAP as a free DAST tool
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0_Core.zip
        unzip ZAP_2.10.0_Core.zip
        ./ZAP_2.10.0/zap.sh -daemon -port 8081
        npm install -g zaproxy
        zaproxy --spider target-url
        zaproxy --active-scan target-url
        zaproxy --report target-url -f json -s dast-report.json

