name: Node.js CI/CD with SAST and DAST 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    
    - name: Install dependencies
      run: npm install

    - name: run application
      run: nohup npm run start &
    - name: run hawkscan
      uses: stackhawk/hawkscan-action@v2.1.2
      with:
        apiKey: ${{ secrets.HAWK_API_KEY }}

